version: 2.1

orbs:
  aws-ecr: circleci/aws-ecr@0.0.2
  aws-ecs: circleci/aws-ecs@0.0.3

anchors:
  - &plan
    docker:
      - image: hashicorp/terraform:0.11.11
    steps:
      - checkout
      - run:
          name: plan
          command: |
            export AWS_ACCESS_KEY_ID=$(eval echo $AWS_ACCESS_KEY)
            export AWS_SECRET_ACCESS_KEY=$(eval echo $AWS_SECRET_KEY)
            terraform init -backend-config="bucket=$(eval echo $AWS_BUCKET_NAME)"
            terraform workspace new ${WORKSPACE} 2>/dev/null || terraform workspace select ${WORKSPACE}
            terraform workspace list
            terraform plan
  - &provisioning
    docker:
      - image: hashicorp/terraform:0.11.11
    steps:
      - checkout
      - run:
          name: provisioning
          command: |
            [[ "$CIRCLE_PULL_REQUEST" ]] && exit 0
            export AWS_ACCESS_KEY_ID=$(eval echo $AWS_ACCESS_KEY)
            export AWS_SECRET_ACCESS_KEY=$(eval echo $AWS_SECRET_KEY)
            terraform init -backend-config="bucket=$(eval echo $AWS_BUCKET_NAME)"
            terraform workspace new ${WORKSPACE} 2>/dev/null || terraform workspace select ${WORKSPACE}
            terraform workspace list
            terraform apply -auto-approve
jobs:
  aws-ecr/build_and_push_image:
    account-url: "$AWS_ACCOUNT_ID.dkr.ecr.$AWS_DEFAULT_REGION.amazonaws.com"
    repo: $AWS_RESOURCE_NAME_PREFIX
    region: $AWS_DEFAULT_REGION
    tag: latest
  plan_stg:
    <<: *plan
    environment:
      WORKSPACE: stg
      AWS_ACCESS_KEY: $AWS_STG_ACCESS_KEY
      AWS_SECRET_KEY: $AWS_STG_SECRET_KEY
      AWS_BUCKET_NAME: $AWS_STG_BUCKET_NAME

  plan_prd:
    <<: *plan
    environment:
      WORKSPACE: prd
      AWS_ACCESS_KEY: $AWS_PRD_ACCESS_KEY
      AWS_SECRET_KEY: $AWS_PRD_SECRET_KEY
      AWS_BUCKET_NAME: $AWS_PRD_BUCKET_NAME

  provisioning_stg:
    <<: *provisioning
    environment:
      WORKSPACE: stg
      AWS_ACCESS_KEY: $AWS_STG_ACCESS_KEY
      AWS_SECRET_KEY: $AWS_STG_SECRET_KEY
      AWS_BUCKET_NAME: $AWS_STG_BUCKET_NAME

  provisioning_prd:
    <<: *provisioning
    environment:
      WORKSPACE: prd
      AWS_ACCESS_KEY: $AWS_PRD_ACCESS_KEY
      AWS_SECRET_KEY: $AWS_PRD_SECRET_KEY
      AWS_BUCKET_NAME: $AWS_PRD_BUCKET_NAME

workflows:
  version: 2
  docker_build:
    jobs:
      - docker_build
  plan_stg:
    jobs:
      - plan_stg:
          requires:
            - docker_build
          filters:
            branches:
              ignore:
                - develop
                - master
  provisioning_stg:
    jobs:
      - plan_stg:
          requires:
            - docker_build
          filters:
            branches:
              only:
                - develop
      - provisioning_stg:
          requires:
            - plan_stg
  provisioning_prd:
    jobs:
      - plan_prd:
          requires:
            - docker_build
          filters:
            branches:
              only:
                - master
      - approve:
          requires:
            - plan_prd
          type: approval
      - provisioning_prd:
          requires:
            - approve
